# Generated by Django 4.2.8 on 2025-05-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'verbose_name': 'EndPoint/Port', 'verbose_name_plural': 'Terminals/Ports'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['path_position']},
        ),
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.device'),
        ),
    ]
