# Generated by Django 4.2.8 on 2025-05-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_interface_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.device'),
        ),
    ]
