# Generated by Django 4.2.8 on 2025-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_outerendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outerendpoint',
            name='path',
        ),
        migrations.AddField(
            model_name='outerendpoint',
            name='device',
            field=models.ManyToManyField(blank=True, null=True, to='info.device'),
        ),
    ]
