# Generated by Django 4.2.8 on 2025-08-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_outerendpoint_path_outerendpoint_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='series',
        ),
    ]
