# Generated by Django 4.2.8 on 2025-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_route_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
