# Generated by Django 4.2.8 on 2025-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_route_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.TextField(max_length=1000),
        ),
    ]
